<?php

namespace OCIM\ContactsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PersonneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonneRepository extends EntityRepository
{
  public function findAll(){
    return $this->findBy(array(), array('id' => 'DESC'));
  }
}
