<?php

namespace OCIM\EvenementsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InscriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InscriptionRepository extends EntityRepository
{
	public function findAllByEvenement($evenement_id)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT i, f FROM OCIMEvenementsBundle:Inscription i
				JOIN i.evenementformule f
				JOIN i.personnes p
				WHERE f.evenement = :id
				AND p INSTANCE OF OCIMContactsBundle:Stagiaire
				ORDER BY i.statut ASC, p.nom ASC'
            )->setParameter('id', $evenement_id)
            ->getResult();
    }
	public function countInscriptionsByEvenement($evenement_id){
		return $this->getEntityManager()
            ->createQuery(
                'SELECT distinct COUNT(i.statut), i.statut FROM OCIMEvenementsBundle:Inscription i
				JOIN i.evenementformule f
				WHERE f.evenement = :id
				GROUP BY i.statut
				'
            )->setParameter('id', $evenement_id)
            ->getResult();
	}

	public function lastInscriptions(){
		return $this->getEntityManager()
            ->createQuery(
        'SELECT i FROM OCIMEvenementsBundle:Inscription i
				JOIN i.personnes p
				WHERE p INSTANCE OF OCIMContactsBundle:Stagiaire
				ORDER BY i.dateInscription DESC'
            )
			->setMaxResults(10)
            ->getResult();
	}

	public function getOrdreMaxByEvenement($evenement_id){
		return $this->getEntityManager()
			->createQuery(
					'SELECT MAX(i.ordre) FROM OCIMEvenementsBundle:Inscription i
					JOIN i.evenementformule f
					WHERE f.evenement = :id'
				)->setParameter('id', $evenement_id)
				->getSingleScalarResult();
	}
}
