<?php

namespace OCIM\EvenementsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ReponsesChampPersoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReponsesChampPersoRepository extends EntityRepository
{

}
