<?php

namespace OCIM\ExportBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TemplateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TemplateRepository extends EntityRepository
{
  public function getLiens(){
    return $this->getEntityManager()
      ->createQuery(
        "SELECT t.id, t.nom FROM OCIMExportBundle:Template t
        WHERE t.type = 'pdf'
        OR t.type = 'convention'
        ORDER BY t.ordre ASC"
      )
      ->getResult();
  }
}
