parameters:
#    ocim_evenements.example.class: OCIM\EvenementsBundle\Example

services:
#    ocim_evenements.example:
#        class: %ocim_evenements.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
