OCIM\EvenementsBundle\Entity\ReponsesChampPerso:
    type: entity
    manyToOne:
        modele:
            targetEntity: ModeleChampPerso
            inversedBy: reponses
            joinColumn:
                name: modele_id
                referencedColumnName: id
        personne:
            targetEntity: OCIM\ContactsBundle\Entity\Personne
            inversedBy: reponsesChampPerso
            joinColumn:
                name: personne_id
                referencedColumnName: id
    table: null
    repositoryClass: OCIM\EvenementsBundle\Entity\ReponsesChampPersoRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        reponse:
            type: boolean
            nullable: true
        reponseText:
            type: string
            length: 255
            nullable: true
        date:
            type: datetime
            nullable: true
    lifecycleCallbacks: {  }
