parameters:
#    ocim_export.example.class: OCIM\ExportBundle\Example

services:
#    ocim_export.example:
#        class: %ocim_export.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
