parameters:
#    ocim_user.example.class: OCIM\UserBundle\Example

services:
#    ocim_user.example:
#        class: %ocim_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
